#def lazy_matrix_mul(m_a, m_b):

>>> lazy_matrix_mul = __import__('101-lazy_matrix_mul').lazy_matrix_mul
>>> def matrix_mul(m_a, m_b):
... 	print(lazy_matrix_mul(m_a, m_b))

>>> matrix_mul([[1, 2], [3, 4]], [[1, 2], [3, 4]])
[[ 7 10]
 [15 22]]


>>> matrix_mul([[3], [6]], [[4, 8]])
[[12 24]
 [24 48]]


>>> matrix_mul([[3]], [[6]])
[[18]]


>>> matrix_mul("5", [[6]])
Traceback (most recent call last):
	  ...
ValueError: Scalar operands are not allowed, use '*' instead


>>> matrix_mul("5", [6])
Traceback (most recent call last):
	  ...
ValueError: Scalar operands are not allowed, use '*' instead


>>> matrix_mul("5", 6)
Traceback (most recent call last):
	  ...
ValueError: Scalar operands are not allowed, use '*' instead


>>> matrix_mul([[6]], "5")
Traceback (most recent call last):
	  ...
ValueError: Scalar operands are not allowed, use '*' instead


>>> matrix_mul([6], "5")
Traceback (most recent call last):
	  ...
ValueError: Scalar operands are not allowed, use '*' instead


>>> matrix_mul([[]], 6)
Traceback (most recent call last):
	  ...
ValueError: Scalar operands are not allowed, use '*' instead


>>> matrix_mul([()], [[6], [()]])
Traceback (most recent call last):
	  ...
ValueError: setting an array element with a sequence.


>>> matrix_mul([()], [[6], [8]])
Traceback (most recent call last):
	  ...
ValueError: shapes (1,0) and (2,1) not aligned: 0 (dim 1) != 2 (dim 0)


>>> matrix_mul([[81], "51", [92]], [[6], [()]])
Traceback (most recent call last):
	  ...
ValueError: setting an array element with a sequence.


>>> matrix_mul([[81], "51"], [[6], [()]])
Traceback (most recent call last):
	  ...
ValueError: setting an array element with a sequence.


>>> matrix_mul([[]], [[6], ()])
Traceback (most recent call last):
	  ...
TypeError: Object arrays are not currently supported


>>> matrix_mul([[81], [""]], [[6], (), [8]])
Traceback (most recent call last):
	  ...
TypeError: Object arrays are not currently supported


>>> matrix_mul([[81], [92]], [7, [6], [()]])
Traceback (most recent call last):
	  ...
ValueError: setting an array element with a sequence.


>>> matrix_mul([], [[6], [()]])
Traceback (most recent call last):
	  ...
ValueError: setting an array element with a sequence.


>>> matrix_mul([["7"]], [[]])
Traceback (most recent call last):
	  ...
TypeError: Cannot cast array data from dtype('float64') to dtype('<U32') according to the rule 'safe'


>>> matrix_mul([[5, 6], [6]], [[]])
Traceback (most recent call last):
	  ...
TypeError: Object arrays are not currently supported


>>> matrix_mul([[81], [""]], [[6], [()]])
Traceback (most recent call last):
	  ...
ValueError: setting an array element with a sequence.


>>> matrix_mul([[81], [""]], [[81], [""]])
Traceback (most recent call last):
	  ...
ValueError: shapes (2,1) and (2,1) not aligned: 1 (dim 1) != 2 (dim 0)


>>> matrix_mul([[81], [""]], [[6], []])
Traceback (most recent call last):
	  ...
TypeError: Object arrays are not currently supported


>>> matrix_mul([[6], [7]], [[81], [""]])
Traceback (most recent call last):
	  ...
ValueError: shapes (2,1) and (2,1) not aligned: 1 (dim 1) != 2 (dim 0)


>>> matrix_mul([[81], [92]], [[6], [()]])
Traceback (most recent call last):
	  ...
ValueError: setting an array element with a sequence.


>>> matrix_mul([[81, 5], [92]], [[6], [()]])
Traceback (most recent call last):
	  ...
ValueError: setting an array element with a sequence.


>>> matrix_mul([[81, 5], [92]], [[6], [7]])
Traceback (most recent call last):
	  ...
TypeError: Object arrays are not currently supported


>>> matrix_mul([[81, 5], [92]], [[6], []])
Traceback (most recent call last):
	  ...
TypeError: Object arrays are not currently supported


>>> matrix_mul([[81], [92]], [[6], []])
Traceback (most recent call last):
	  ...
TypeError: Object arrays are not currently supported


>>> matrix_mul([[61]], [[81], [92]])
Traceback (most recent call last):
	  ...
ValueError: shapes (1,1) and (2,1) not aligned: 1 (dim 1) != 2 (dim 0)


>>> matrix_mul([[81], [92]], [[61], [79]])
Traceback (most recent call last):
	  ...
ValueError: shapes (2,1) and (2,1) not aligned: 1 (dim 1) != 2 (dim 0)


>>> matrix_mul([[81], [92]], [[], []])
Traceback (most recent call last):
	  ...
ValueError: shapes (2,1) and (2,0) not aligned: 1 (dim 1) != 2 (dim 0)


>>> matrix_mul([[81, 92]], [[61], [79]])
[[12209]]
